name: Assignment1

on:
  push:
    branches:
      - main
      - 'feature/*'  # Trigger on feature branch pushes
  pull_request:
    branches:
      - main
      - 'feature/*'  # Trigger on PR to main or feature branches

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Checkout the code from the repository
      - name: Checkout code
        uses: actions/checkout@v3

      # Set up JDK 21 (latest LTS version at the time)
      - name: Set up JDK 21
        uses: actions/setup-java@v3
        with:
          java-version: '21'
          distribution: 'temurin'

      # Cache Maven dependencies to speed up builds
      - name: Cache Maven dependencies
        uses: actions/cache@v3
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-

      # Run Maven build and test
      - name: Build and test with Maven
        run: mvn clean install

      #Upload the WAR file as an artifact for Jenkins to use
      - name: Upload WAR file
        uses: actions/upload-artifact@v3
        with:
          name: war-file
          path: target/*.war

     
